version: "1.0"
info:
  model: int-scaffold
packages:
- name: KMAT_ORIGIN_LDSProject
  gitServerName: Karthik
  gitUrl: https://github.com/karthikbm/KMAT_ORIGIN_LDSProject
  gitUsername: karthikbm
  gitBranch: main
- name: OriginKMAT_Jun2024
  gitServerName: Karthik
  gitUrl: https://github.com/karthikbm
  gitUsername: karthikbm
  gitBranch: main
